# -*- coding: utf-8 -*-
"""myco-forecasting-model-training.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Vt41q2_xtFB0A_cs786jOrDvJKeb5LEt
"""

# --- Install dependencies ---
!pip install scikit-learn pandas numpy

# --- Imports ---
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import RandomForestRegressor

# --- Helper function ---
def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))

# --- Load and prepare data ---
csv_path = "/content/timeseries-dataset.csv"  # upload your file to Colab first
df = pd.read_csv(csv_path)

# Use columns 1, 2, 3 to predict column 7 (1-based indexing)
feature_cols_1based = [1, 2, 3]
target_col_1based = 7
X_iloc = [i - 1 for i in feature_cols_1based]
y_iloc = target_col_1based - 1

work = df.iloc[:, X_iloc + [y_iloc]].apply(pd.to_numeric, errors="coerce")
clean = work.dropna(axis=0).reset_index(drop=True)

X = clean.iloc[:, :len(X_iloc)].values
y = clean.iloc[:, -1].values

print(f"Dataset after cleaning: {len(clean)} samples, {len(X_iloc)} features")

# --- Train/test split (80/20) ---
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train size: {len(X_train)} | Test size: {len(X_test)}")

# --- Define models ---
models = {
    "Linear Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LinearRegression())
    ]),
    "KNN": Pipeline([
        ("scaler", StandardScaler()),
        ("model", KNeighborsRegressor(n_neighbors=5))
    ]),
    "Random Forest": Pipeline([
        ("model", RandomForestRegressor(
            n_estimators=300, random_state=42, n_jobs=-1))
    ]),
}

# --- Fit and evaluate each model ---
results = []
for name, model in models.items():
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    model_rmse = rmse(y_test, preds)
    model_r2 = r2_score(y_test, preds)
    results.append({
        "Model": name,
        "RMSE": model_rmse,
        "R²": model_r2
    })
    print(f"\n{name}:")
    print(f"  RMSE = {model_rmse:.6f}")
    print(f"  R²   = {model_r2:.6f}")

# --- Display results summary ---
results_df = pd.DataFrame(results).sort_values("RMSE")
print("\n=== 80/20 Split Results Summary ===")
print(results_df.to_string(index=False))