# -*- coding: utf-8 -*-
"""intra-prompt-average-generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RELK4XLEbQ1ESwvEKhPAkpzC_By9ugd
"""

import pandas as pd

# Load your normalized dataset
df = pd.read_csv("/content/newexperiments_prompt_sensitity_normalized.csv")

# Identify columns for each prompt type
baseline_cols = [c for c in df.columns if c.startswith("baseline") and c.endswith("_score")]
fewshot_cols = [c for c in df.columns if c.startswith("few_shot") and c.endswith("_score")]
cot_cols = [c for c in df.columns if c.startswith("cot") and c.endswith("_score")]

# Compute per-row averages
df_avgs = pd.DataFrame({
    "baseline_avg": df[baseline_cols].mean(axis=1),
    "few_shot_avg": df[fewshot_cols].mean(axis=1),
    "cot_avg": df[cot_cols].mean(axis=1),
})

# (Optional) Keep identifiers like filename if they exist
id_like_cols = [c for c in ["id", "filename", "title"] if c in df.columns]
if id_like_cols:
    df_avgs = pd.concat([df[id_like_cols], df_avgs], axis=1)

# Save to CSV
out_path = "experiments_prompt_analysis_avgs.csv"
df_avgs.to_csv(out_path, index=False)

print(f"Saved per-row averages to {out_path}")
print(df_avgs.head())

# ============================================
# 📊 Prompt Score Distribution Visualizer
# ============================================
# This code reads a CSV with three normalized score columns
# (e.g., baseline_avg, few_shot_avg, cot_avg)
# and plots their score distributions as histograms.
# --------------------------------------------

import pandas as pd
import matplotlib.pyplot as plt

# === USER SETTINGS ===
# Upload your CSV in Colab or set path if stored in Drive
# Example: from google.colab import files; files.upload()
csv_path = "/content/papers2_rows_prompt_avgs.csv"  # <- Replace with your file name

# Column names for prompt scores
prompt_cols = ["baseline_avg", "few_shot_avg", "cot_avg"]

# === LOAD DATA ===
df = pd.read_csv(csv_path)

# === SUMMARY ===
print("Loaded data shape:", df.shape)
print("Columns available:", list(df.columns))
print("\nBasic stats:\n", df[prompt_cols].describe())

# === HISTOGRAMS ===
plt.figure(figsize=(10, 5))

# Define common bins and colors
bins = 30
colors = ["#1f77b4", "#2ca02c", "#ff7f0e"]

for col, color in zip(prompt_cols, colors):
    plt.hist(df[col], bins=bins, alpha=0.5, label=col, color=color, edgecolor="black")

plt.title("Distribution of Normalized Scores per Prompt - Mycoremediation Query", fontsize=14)
plt.xlabel("Normalized Score (0–1)")
plt.ylabel("Frequency")
plt.legend(title="Prompt")
plt.grid(axis="y", linestyle="--", alpha=0.6)
plt.tight_layout()
plt.show()

# === OPTIONAL: SAVE PLOT ===
# plt.savefig("prompt_score_distributions.png", dpi=300)

# ============================================
# 🔗 Prompt Correlation Heatmap
# ============================================
# Computes Pearson correlations between baseline, few-shot,
# and chain-of-thought average scores, then plots a heatmap.
# --------------------------------------------

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# === USER SETTINGS ===
csv_path = "/content/experiments_prompt_analysis_avgs.csv"  # <- replace with your actual filename
prompt_cols = ["baseline_avg", "few_shot_avg", "cot_avg"]

# === LOAD DATA ===
df = pd.read_csv(csv_path)
df = df[prompt_cols].dropna()  # ensure clean correlations

# === COMPUTE CORRELATION MATRIX ===
corr_matrix = df.corr(method="pearson")

print("=== Pearson Correlation Matrix ===")
print(corr_matrix.round(3))

# === PLOT HEATMAP ===
plt.figure(figsize=(5, 4))
plt.imshow(corr_matrix, cmap="coolwarm", vmin=0, vmax=1)
plt.colorbar(label="Pearson r")

# Add labels
plt.xticks(np.arange(len(prompt_cols)), prompt_cols, rotation=45, ha="right")
plt.yticks(np.arange(len(prompt_cols)), prompt_cols)
plt.title("Experiments Prompt–Prompt Pearson Correlations", fontsize=13)

# Annotate values on heatmap
for i in range(len(prompt_cols)):
    for j in range(len(prompt_cols)):
        plt.text(j, i, f"{corr_matrix.iloc[i, j]:.2f}",
                 ha="center", va="center", color="black", fontsize=10)

plt.tight_layout()
plt.show()

# === OPTIONAL: SAVE ===
# plt.savefig("prompt_correlation_heatmap.png", dpi=300)