# -*- coding: utf-8 -*-
"""normalize-intra-prompt-analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwx5jHQLELSLOz5apMIKyLG8YjiPka-C
"""

import pandas as pd

# Load dataset
df = pd.read_csv("/content/experiment-content-prompt-analysis - explanations_removed.csv")

# Identify score columns
score_cols = [c for c in df.columns if c.endswith("_score")]

# Normalize each score column (min-max scaling)
df_normalized = df.copy()
df_normalized[score_cols] = (
    df[score_cols] - df[score_cols].min()
) / (df[score_cols].max() - df[score_cols].min())

# Check first few rows of normalized scores
print(df_normalized[score_cols].head())

# Optionally save to a new CSV
df_normalized.to_csv("newexperiments_prompt_sensitity_normalized.csv", index=False)

